version: '3.8'

services:
  rabbit1:
    image: rabbitmq:3.10.6-management
    hostname: rabbit1
    container_name: rabbit1
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=shoalter
    volumes:
      - ./docker_rabbitmq1_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  rabbit2:
    image: rabbitmq:3.10.6-management
    hostname: rabbit2
    container_name: rabbit2
    restart: always
    depends_on:
      - rabbit1
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=shoalter
    volumes:
      - ./docker_rabbitmq2_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  rabbit3:
    image: rabbitmq:3.10.6-management
    hostname: rabbit3
    container_name: rabbit3
    restart: always
    depends_on:
      - rabbit1
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=shoalter
    volumes:
      - ./docker_rabbitmq3_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
