version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo5
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root