version: "3.8"

services:
  mysql8:
    image: mysql/mysql-server:8.0
    container_name: mysql-8
    restart: always
    volumes:
      - ./docker_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Hong_Kong
    ports:
      - "3306:3306"