version: '3.8'

services:
  rabbit1:
    image: rabbitmq:3.10.6-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker_rabbitmq_data:/var/lib/rabbitmq
