version: '3.8'

services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 30001:27017 
    restart: always
    volumes:
      - ./mongo1_data:/data/db
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    command: mongod --replSet product-master-mongo-set
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 30002:27017
    restart: always
    volumes:
      - ./mongo2_data:/data/db
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    command: mongod --replSet product-master-mongo-set
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 30003:27017
    restart: always
    volumes:
      - ./mongo3_data:/data/db
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    command: mongod --replSet product-master-mongo-set
  mongoinit:
    image: mongo:5.0
    restart: "no"
    depends_on:
      mongo1: 
        condition: service_healthy
      mongo2: 
        condition: service_healthy
      mongo3: 
        condition: service_healthy
    command: >
      mongo --host mongo1:27017 --eval 
      '
      config = {
      "_id" : "product-master-mongo-set",
      "members" : [
        {
          "_id" : 0,
          "host" : "mongo1:27017"
        },
        {
          "_id" : 1,
          "host" : "mongo2:27017"
        },
        {
          "_id" : 2,
          "host" : "mongo3:27017"
        }
      ]
      };
      rs.initiate(config);
      '